/********************************************************************
* ./src/RootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./src/RootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRootDict();
extern void G__cpp_setup_inheritanceRootDict();
extern void G__cpp_setup_typetableRootDict();
extern void G__cpp_setup_memvarRootDict();
extern void G__cpp_setup_globalRootDict();
extern void G__cpp_setup_memfuncRootDict();
extern void G__cpp_setup_funcRootDict();
extern void G__set_cpp_environmentRootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RootDataStructures.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RootDictLN_BetaDataStructure;
extern G__linked_taginfo G__RootDictLN_LogicDataStructure;
extern G__linked_taginfo G__RootDictLN_RuntimeDataStructure;
extern G__linked_taginfo G__RootDictLN_LiquidDataStructure;
extern G__linked_taginfo G__RootDictLN_VandleDataStructure;

/* STUB derived class for protected member access */
